config/routes.rb
Rails.application.routes.draw do

  scope module: 'admin' do
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
end

  scope module: 'users' do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  end

  resources :users, except: [:create,:destroy,:new] do
    member do
      get 'pets' => 'users#pets_index'
      get 'followers'
      get 'followings'
      get 'confirm'
      delete 'cancel'
    end
    collection do
      get 'cancel_done'
    end
    resource :relationships, only: [:create,:destroy]
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create,:destroy]
  end
  resources :pets
  root "homes#index"
  get "/about" => "homes#about"

  namespace :admins do
    root 'top#top'
    resources :genres, only: [:index,:create,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    has_many :posts, dependent: :destroy
    enum sex: {男の子:0, 女の子:1}

    attachment :image

    with_options presence: true do
        validates :name
        validates :sex
        validates :age
        validates :image
        validates :genre_id
    end

    validates :introduction, length: { maximum: 1500 }
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    before_action :authenticate_user!, except: [:index]

    def new
        @pet = Pet.new
    end

    def index
        @pets = Pet.all
    end

    def create
        @pet = Pet.new(pet_params)
        @pet.sex = params[:pet][:sex].to_i
        @pet.user_id = current_user.id
        if @pet.save
            redirect_to pet_path(@pet.id)
        else
            render :new
        end
    end

    def show
        @pet = Pet.find(params[:id])
    end

    def edit
        @pet = Pet.find(params[:id])
        if @pet.user != current_user
            redirect_to pet_path(@pet)
        end
    end

    def update
        @pet = Pet.find(params[:id])
        @pet.sex = params[:pet][:sex].to_i
        if @pet.update(pet_params)
            redirect_to pet_path(@pet.id)
        else
            render 'edit'
        end
    end

    def destroy
    end

    private
    
    def pet_params
        params.require(:pet).permit(:genre_id,:name,:introduction,:age,:image)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/edit.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1><%= @pet.name %>編集ページ</h1>
        <%= form_with model: @pet, local: true do |f| %>

            <div class="field">
                お名前<%= f.text_field :name, autofocus: true, autocomplete: "name" %>
            </div>

            <div class="field">
                性別
                <%= f.radio_button :sex,0, checked: "checked" %>男
                <%= f.radio_button :sex,1 %>女
            </div>

            <div class="field">
                年齢<%= f.number_field :age, min: 0 %>
            </div>

            <div class="field">
                写真<%= f.attachment_field :image %>
            </div>

            <div class="field">
                紹介文<%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
            </div>

            <div class="field">
                カテゴリ<%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "選択してください" %>
            </div>

            <%= f.submit "更新" %>

        <% end %>
</div>

app/views/pets/index.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>みんなのうちの子ページ</h1>

        <table class="table">
            <thead>
                <th></th>
                <th>お名前</th>
                <th>紹介文</th>
                <th>性別</th>
                <th>年齢</th>
                <th>カテゴリ</th>
                <th></th>
            </thead>
            <% @pets.each do |pet| %>
            <tbody>
                <tr>
                        <td>
                            <%= link_to pet_path(pet) do %>
                                <%= attachment_image_tag pet, :image, size: "100x100", class: "radius" %>
                            <% end %>
                        </td>
                        <td>
                            <%= pet.name %>
                        </td>
                        <td><%= pet.introduction.truncate(30) %></td>
                        <td><%= pet.sex %></td>
                        <td><%= pet.age %>才</td>
                        <td><%= pet.genre.name %></td>
                        <td>
                            <%= link_to user_path(pet.user), class: "test5" do %>
                                <%= attachment_image_tag pet.user, :image, size: "50x50", class: "radius" %>
                            <% end %>
                            <%= pet.user.name %>さんの家族
                        </td>
                    <% end %>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/pets/new.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>うちの子新規登録ページ</h1>
        <%= form_with model: @pet, local: true do |f| %>

            <div class="field">
                お名前<%= f.text_field :name, autofocus: true, autocomplete: "name" %>
            </div>

            <div class="field">
                性別
                <%= f.radio_button :sex,0, checked: "checked" %>男
                <%= f.radio_button :sex,1 %>女
            </div>

            <div class="field">
                年齢<%= f.number_field :age, min: 0 %>
            </div>

            <div class="field">
                写真<%= f.attachment_field :image %>
            </div>

            <div class="field">
                紹介文<%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
            </div>

            <div class="field">
                カテゴリ<%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "選択してください" %>
            </div>

            <%= f.submit "新規登録" %>

        <% end %>
</div>

app/views/pets/show.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1><%= @pet.name %>のページ</h1>
    <div class="row">
        <div class="col-4">
            <p><%= attachment_image_tag @pet, :image, size: "300x300", class: "radius" %></p>
            <p>お名前:&emsp;<%= @pet.name %></p>
            <p>性別:&emsp;<%= @pet.sex %></p>
            <p>年齢:&emsp;<%= @pet.age %>才</p>
            <p>
                <% if @pet.user == current_user %>
                    <%= link_to "編集ページへ", edit_pet_path(@pet.id), class: "change-link-color" %>
                <% end %>
            </p>
        </div>
        <div class="col-8">
            <div>
                <span>紹介文</span>
                <p><%= @pet.introduction %></p>
            </div>
        </div>
    </div>
    <h1><%= @pet.name %>の投稿一覧</h1>
    <div>
            <% @pet.posts.each do |post| %>
            <div class="test">
                <span>
                    <%= link_to post_path(post), class: "change-link-color" do %>
                    <%= attachment_image_tag post, :image, size: "200x200", class: "radius" %>
                </span>
                <p><%= post.title %></p>
                <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>