config/routes.rb
Rails.application.routes.draw do

  scope module: 'admin' do
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
end

  scope module: 'users' do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  end

  resources :users, except: [:create,:destroy,:new] do
    member do
      get 'pets' => 'users#pets_index'
      get 'followers'
      get 'followings'
      get 'confirm'
      delete 'cancel'
    end
    collection do
      get 'cancel_done'
    end
    resource :relationships, only: [:create,:destroy]
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create,:destroy]
  end
  resources :pets
  root "homes#index"
  get "/about" => "homes#about"

  namespace :admins do
    root 'top#top'
    resources :genres, only: [:index,:create,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :pets, dependent: :destroy
    validates :name, presence: true, uniqueness: true
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController

    before_action :authenticate_admin!

    def index
        @genres = Genre.all
        @genre = Genre.new
    end

    def create
        @genre = Genre.new(genre_params)
        if @genre.save
            redirect_to admins_genres_path
        else
            @genres = Genre.all
            render 'index'
        end
    end

    def edit
        @genre = Genre.find(params[:id])
    end

    def update
        @genre = Genre.find(params[:id])
        if @genre.update(genre_params)
            redirect_to admins_genres_path
        else
            render 'edit'
        end
    end

    private

    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>ジャンル編集ページ</h1>

        <%= form_with model: @genre, url: admins_genre_path(@genre), local: true do |f| %>

        <%= f.text_field :name %>

        <%= f.submit '名前変更' %>

        <% end %>
    </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>ジャンル一覧ページ</h1>

        <%= form_with model: @genre, url: admins_genres_path, local: true do |f| %>
            ジャンル名
            <%= f.text_field :name %>
            <%= f.submit '追加' %>
        <% end %>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ジャンル</th>
                    <th scope="col">編集</th>
                </tr>
            </thead>
            <tbody>
            <% @genres.each do |genre| %>
                <tr>
                    <td><%= genre.name %></td>
                    <td><%= link_to "編集", edit_admins_genre_path(genre.id) %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>