config/routes.rb
Rails.application.routes.draw do

  scope module: 'admin' do
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
end

  scope module: 'users' do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  end

  resources :users, except: [:create,:destroy,:new] do
    member do
      get 'pets' => 'users#pets_index'
      get 'followers'
      get 'followings'
      get 'confirm'
      delete 'cancel'
    end
    collection do
      get 'cancel_done'
    end
    resource :relationships, only: [:create,:destroy]
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create,:destroy]
  end
  resources :pets
  root "homes#index"
  get "/about" => "homes#about"

  namespace :admins do
    root 'top#top'
    resources :genres, only: [:index,:create,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

        acts_as_paranoid

        has_many :pets, dependent: :destroy
        has_many :posts, dependent: :destroy
        has_many :post_comments, dependent: :destroy
        has_many :favorites, dependent: :destroy

        attachment :image

        validates :name, presence: true

        #フォロワー
        has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followee_id'
        has_many :followers, through: :reverse_of_relationships, source: :follower

        #フォローしてる人
        has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id'
        has_many :followings, through: :relationships, source: :followee

        def following?(another_user)
          self.followings.include?(another_user)
        end
      
        def follow(another_user)
          unless self == another_user
            self.relationships.find_or_create_by(followee_id: another_user.id, follower_id: self.id)
          end
        end
        
        def unfollow(another_user)
          unless self == another_user
            relationship = self.relationships.find_by(followee_id: another_user.id, follower_id: self.id)
            relationship.destroy if relationship
          end
        end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:index, :cancel_done]
    before_action :authenticate_admin!, only: [:index]

    def show
        @user = User.find(params[:id])
        @pets = @user.pets
        @posts = @user.posts
    end

    def edit
        @user = User.find(params[:id])
        if @user != current_user
            redirect_to user_path(@user)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    def index
        @users = User.all
    end

    def confirm
        @user = User.find(params[:id])
    end

    def cancel
        @user = User.find(params[:id])
        @user.destroy
        redirect_to cancel_done_users_path
    end

    def cancel_done
    end

    def pets_index
        @user = User.find(params[:id])
        @pets = @user.pets
    end

    def followings
        @user = User.find(params[:id])
    end

    def followers
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:name,:introduction,:image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cancel_done.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>退会処理されました</h1>

        <p>
            退会処理が完了しました。<br>
            うちの子。を使っていただきありがとうございました！<br>
            また可愛いうちの子を自慢したくなったら<br>
            戻ってきてくださいね。
        </p>
        <%= link_to "うちの子。トップページへ", root_path %>
    </div>
</div>

app/views/users/confirm.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>退会ページ</h1>

        <p>
            本当に退会しますか？<br>
            退会すると、登録したうちの子や投稿した記事が消去されます。<br>
            退会する場合は『退会する』を押してください。
        </p>
        <p><%= link_to "退会しない", user_path(@user) %></p>
        <p><%= link_to "退会する", cancel_user_path(@user), method: :delete %></p>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>ユーザー編集ページ</h1>

        <%= form_with model: @user, local: true do |f|  %>

        <div class="field">
            お名前<%= f.text_field :name %>
        </div>

        <div class="field">
            プロフィール画像<%= f.attachment_field :image %>
        </div>

        <div class="field">
            紹介文<%= f.text_area :introduction %>
        </div>

        <%= f.submit "更新する" %>
        <% end %>

        <%= link_to "退会する", confirm_user_path(@user) %>
    </div>
</div>

app/views/users/followers.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1><%= @user.name %>のフォロワー一覧</h1>

        <div>
            <% @user.followers. each do |follower| %>
                <%= attachment_image_tag follower, :image, size: "50x50", class: "radius" %>
                <%= follower.name %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/followings.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1><%= @user.name %>がフォローしている人</h1>

        <div>
            <% @user.followings. each do |following| %>
                <%= attachment_image_tag following, :image, size: "50x50", class: "radius" %>
                <%= following.name %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <h1>会員様一覧ページ</h1>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">ユーザー名</th>
                    <th scope="col">メールアドレス</th>
                    <th scope="col">ステータス</th>
                </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
                <tr>
                    <th scope="row">画像</th>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td>nil</td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/users/pets_index.html.erb
<div class="container contain2">
    <div class="hukidasi">
        <% if @user == current_user %>
            <h1>あなたのうちの子一覧ページ</h1>
        <% else %>
            <h1><%= @user.name %>さんのうちの子一覧ページ</h1>
        <% end %>

        <table class="table">
            <tbody>
                <tr>
                <div class="border-design"></div>
                    <% @pets.each do |pet| %>

                        <p>
                            <%= link_to pet_path(pet) do %>
                                <%= attachment_image_tag pet, :image, size: "250x250", class: "radius" %>
                            <% end %>
                        </p>
                        <p>お名前:&emsp;<%= pet.name %></p>
                        <p>性別:&emsp;<%= pet.sex %></p>
                        <p>年齢:&emsp;<%= pet.age %>才</p>
                        <div class="maste">
                        <span class="tape">紹介文</span>
                            <p><%= pet.introduction %></p>
                        </div>
                        <div class="border-design"></div>
                    <% end %>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="container contain2">
    <div class="contain2">
        <div class="hukidasi">
            <h1>
                <% if @user == current_user %>
                    マイページ
                <% else %>
                    <%= @user.name %>さんのページ
                <% end %>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <p><%= attachment_image_tag @user, :image, size: "300x300", class: "radius" %></p>
            お名前&emsp;<%= @user.name %>
            <p><%= link_to "#{@user.followings.count}フォロー", followings_user_path(@user), class: "change-link-color" %></p>
            <p><%= link_to "#{@user.followers.count}フォロワー", followers_user_path(@user), class: "change-link-color" %></p>
            <p>
                <% if current_user == @user %>
                    <%= link_to "編集ページへ", edit_user_path(@user.id), class: "change-link-color" %>
                <% end %>
            </p>
            <p>
                <% unless current_user == @user %>
                    <% if current_user.following?(@user) %>
                        <%= link_to "フォローを外す", user_relationships_path(@user), method: :delete, class:"btn btn-default"%>
                    <% else %>
                        <%= link_to "フォローする", user_relationships_path(@user), method: :post, class:"btn btn-primary"%>
                    <% end %>
                <% end %>
            </p>
        </div>
        <div class="col-8">
            <% if @user.introduction == nil %>
                <p>まだ紹介文がありません</p>
            <% else %>
            <div>
                <span>紹介文</span>
                <p><%= @user.introduction %></p>
            </div>
            <% end %>
        </div>
    </div>
    <div class="contain2 hukidasi">
        <% if @user == current_user %>
            <h1>うちの子</h1>
        <% else %>
            <h1><%= @user.name %>さんちの子</h1>
        <% end %>

        <% if @pets.empty? %>
            <p>まだうちの子登録されていません</p>
            <p><%= link_to "うちの子登録ページへ", new_pet_path, class: "change-link-color" %></p>
        <% else %>
        <table class="table">
            <thead>
                <th></th>
                <th>お名前</th>
                <th>紹介文</th>
                <th>性別</th>
                <th>年齢</th>
                <th>カテゴリ</th>
                <th></th>
            </thead>
            <tr>
            <% @pets.each do |pet| %>
            <tbody>
                <td><%= attachment_image_tag pet, :image, size: "100x100", class: "radius" %></td>
                <td><%= pet.name %></td>
                <td><%= pet.introduction.truncate(35) %></td>
                <td><%= pet.sex %></td>
                <td><%= pet.age %>才</td>
                <td><%= pet.genre.name %></td>
            <% end %>
            </tr>
            </tbody>
        </table>
        <% end %>

        <h1>投稿一覧</h1>
        <% if @posts.empty? %>
            <p>まだ投稿をされていません</p>
            <p><%= link_to "新規投稿ページへ", new_post_path, class: "change-link-color" %></p>
        <% else %>
        <div>
            <% @posts.each do |post| %>
            <div class="test">
                <p>
                    <%= link_to user_path(post.user), class: "change-link-color" do %>
                        <%= attachment_image_tag post.user, :image, size: "50x50", class: "radius" %>
                        <%= post.user.name %>
                    <% end %>
                </p>
                <span>
                    <%= link_to post_path(post), class: "change-link-color" do %>
                    <%= attachment_image_tag post, :image, size: "200x200", class: "radius" %>
                </span>
                <p><%= post.title %></p>
                <% end %>
                </div>
            <% end %>
        </div>
        <% end %>

    </div>
</div>