config/routes.rb
Rails.application.routes.draw do

  scope module: 'admin' do
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
end

  scope module: 'users' do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  end

  resources :users, except: [:create,:destroy,:new] do
    member do
      get 'pets' => 'users#pets_index'
      get 'followers'
      get 'followings'
      get 'confirm'
      delete 'cancel'
    end
    collection do
      get 'cancel_done'
    end
    resource :relationships, only: [:create,:destroy]
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create,:destroy]
  end
  resources :pets
  root "homes#index"
  get "/about" => "homes#about"

  namespace :admins do
    root 'top#top'
    resources :genres, only: [:index,:create,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

    belongs_to :user
    belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :pets, dependent: :destroy
    validates :name, presence: true, uniqueness: true
end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    has_many :posts, dependent: :destroy
    enum sex: {男の子:0, 女の子:1}

    attachment :image

    with_options presence: true do
        validates :name
        validates :sex
        validates :age
        validates :image
        validates :genre_id
    end

    validates :introduction, length: { maximum: 1500 }
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :pet
    belongs_to :user

    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    attachment :image

    with_options presence: true do
        validates :title
        validates :body
        validates :pet_id
    end

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

    belongs_to :user
    belongs_to :post

    validates :body, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followee, class_name: "User"

    validates :follower_id, presence: true
    validates :followee_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

        acts_as_paranoid

        has_many :pets, dependent: :destroy
        has_many :posts, dependent: :destroy
        has_many :post_comments, dependent: :destroy
        has_many :favorites, dependent: :destroy

        attachment :image

        validates :name, presence: true

        #フォロワー
        has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followee_id'
        has_many :followers, through: :reverse_of_relationships, source: :follower

        #フォローしてる人
        has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id'
        has_many :followings, through: :relationships, source: :followee

        def following?(another_user)
          self.followings.include?(another_user)
        end
      
        def follow(another_user)
          unless self == another_user
            self.relationships.find_or_create_by(followee_id: another_user.id, follower_id: self.id)
          end
        end
        
        def unfollow(another_user)
          unless self == another_user
            relationship = self.relationships.find_by(followee_id: another_user.id, follower_id: self.id)
            relationship.destroy if relationship
          end
        end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    before_action :authenticate_user!, except: [:index]

    def new
        @pet = Pet.new
    end

    def index
        @pets = Pet.all
    end

    def create
        @pet = Pet.new(pet_params)
        @pet.sex = params[:pet][:sex].to_i
        @pet.user_id = current_user.id
        if @pet.save
            redirect_to pet_path(@pet.id)
        else
            render :new
        end
    end

    def show
        @pet = Pet.find(params[:id])
    end

    def edit
        @pet = Pet.find(params[:id])
        if @pet.user != current_user
            redirect_to pet_path(@pet)
        end
    end

    def update
        @pet = Pet.find(params[:id])
        @pet.sex = params[:pet][:sex].to_i
        if @pet.update(pet_params)
            redirect_to pet_path(@pet.id)
        else
            render 'edit'
        end
    end

    def destroy
    end

    private
    
    def pet_params
        params.require(:pet).permit(:genre_id,:name,:introduction,:age,:image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def new
        @post = Post.new
        @user = current_user
        @pets = @user.pets
    end

    def index
        @posts = Post.all
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to post_path(@post.id)
        else
            render 'new'
        end
    end

    def show
        @post = Post.find(params[:id])
        @post_comments = @post.post_comments
        @user = @post.user
        @pet = @post.pet
        @post_comment = PostComment.new
    end

    def edit
        @post = Post.find(params[:id])
        @user = @post.user
        if @user != current_user
            redirect_to post_path(@post.id)
        end
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to post_path(@post.id)
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private

    def post_params
        params.require(:post).permit(:title,:body,:image,:pet_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:index, :cancel_done]
    before_action :authenticate_admin!, only: [:index]

    def show
        @user = User.find(params[:id])
        @pets = @user.pets
        @posts = @user.posts
    end

    def edit
        @user = User.find(params[:id])
        if @user != current_user
            redirect_to user_path(@user)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    def index
        @users = User.all
    end

    def confirm
        @user = User.find(params[:id])
    end

    def cancel
        @user = User.find(params[:id])
        @user.destroy
        redirect_to cancel_done_users_path
    end

    def cancel_done
    end

    def pets_index
        @user = User.find(params[:id])
        @pets = @user.pets
    end

    def followings
        @user = User.find(params[:id])
    end

    def followers
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:name,:introduction,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uchinoko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>うちの子。</title>
  </head>

  <body class= "all">

  <header class="sticky-top">
  <nav class="navbar navbar-expand-lg header-css">
    <div class="container">
    <% if admin_signed_in? %>
      <%= image_tag('rabbit_color.png', :size => '50x70') %><%= link_to "うちの子。", admins_root_path, class: "logobig" %><%= image_tag('marmot_color.png', :size => '70x50') %>
    <% else %>
    <%= image_tag('rabbit_color.png', :size => '50x70') %><%= link_to "うちの子。", root_path, class: "logobig" %><%= image_tag('marmot_color.png', :size => '70x50') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <% if admin_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "会員様一覧", users_path, class: "header-logo" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admins_genres_path, class: "header-logo" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "header-logo" %>
          </li>
        </ul>
      <% elsif user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "投稿一覧", posts_path, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "みんなのうちの子", pets_path, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "うちの子一覧", pets_user_path(current_user), class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: "header-logo userlogo" do %>
          <i class="fa fa-user-circle"></i>
          <% end %>
        </li>
      </ul>
      <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "みんなのうちの子", pets_path, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿一覧", posts_path, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "うちの子とは", about_path, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "header-logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "header-logo" %>
        </li>
      </ul>
      <% end %>
    </div>
    </div>
  </nav>
  </header>

  <%= yield %>

  <footer class="footerdesign">
    <div class="container footer-design">
    <%= link_to "うちの子。", root_path, class: "footer-main-logo" %>
      <div class="row">
        <div class="col-4">
          <%= link_to "うちの子。とは？", about_path, class: "footer-logo" %><br>
          <%= link_to "サイトマップ", root_path, class: "footer-logo" %>
        </div>
        <div class="col-4">
          <p class="abouthikari">うちの子。を作った人</p>
          <span>岡ひかり / HIKARI OKA</span><br>
          <%= image_tag('Github.png', :size => '50x50', class: "footer-logo") %>
          <%= image_tag('twitter.png', :size => '50x50', class: "footer-logo") %>
          <%= image_tag('Instagram.png', :size => '50x50', class: "footer-logo") %>
        </div>
        <div class="col-4">
          <p>お問い合わせはこちら</p>
          <%= link_to "お問い合わせフォーム", root_path, class: "footer-logo" %>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>